### ISSUE TITLE
file path incorrect

### ISSUE THREAD

**Issue by kiankyars** [Minimel/StochasticBatchAL#1]
Salut, j'ai vu que Configs/experiment/hippocampus_indices, Configs/experiment/prostate_indices qui se trouvent dans le readme n'ont pas le bon chemin de fichier. Ça devrait être plutôt /Configs/init_indices/hippocampus_indices à moins que je ne me trompe. Merci!

**Comment by Minimel** [comment]
Oui tu as raison; merci!
